
 
<html>
<head><title>Get Risk Score</title></head>
 <body>
   	
<link rel="stylesheet" type="text/css" href="Style.css">


<?php
    // first establish the variables that represent student attributes
  

 
    $Unum = $_POST["inputUnum"] ; // this is from the POST generated by INDEX.php
    $Fname = "DEFAULT" ;
    $Lname = "PERSON" ;
    $Hsgpa = 0.0;
    $Hsaverage = 100.00;
    $satmath = 800;
    $satverb = 800;
    $composite = 1600;
    $major = "CIS";
    
    //class input from user 
    
    $classinput = $_POST["inputClass"]; 
    //varibale for risk score
    $riskScore = 0; 
   
  
   echo "<p2>--Retrieving data--</p2><br><br>";
    // now, establish a connection to the database
   
	$servername = "localhost";
        $username = "rsuser";
        $password = "rs2017";
	$dbname = "rs_db";

    $connection = new mysqli($servername, $username, $password, $dbname);
    // Verify Connection to database, else throw error
      if ($conn->connect_error) {
      die("Connection failed: " . $conn->connect_error);
        } 
      $query = "SELECT * FROM student_data WHERE Unum = '".$Unum."'";
     $result = $connection->query($query);

   if ($result->num_rows > 0) {
    // Output Student U-Number and name for verification
    while($row = $result->fetch_assoc()) {
        echo "<p2>U-Number: " . $row["Unum"]. " <br> Name: " . $row["Fname"]. " " . $row["Lname"]. "</p2><br>";
       
       //Set vars equal to database fields
        $Fname = $row["Fname"];
        $Hsgpa = $row["Hsgpa"];
        $Hsaverage = $row["Hsaverage"];
        $satmath = $row["satmath"];
	$satverb = $row["satverb"];
        $composite = $row["composite"];
	$major = $row["major"];
    }
} else {
    echo "<p>--No Data For This U-Number--</p><br><br> <p2>--Check U-Number--</p2><br>";
}

     $connection->close();


    






	//test to make sure varibles are populated (comment out after testing)
/*echo "<br><br>";
echo $Hsgpa;
echo $satmath;
echo $satverb;*/


    // now, select a function based on the user's input

if($Fname == "DEFAULT"){echo "press browser's back button and try again";}
else{
    
    switch ($classinput){
      
      case "select":
        echo "please select a class to assess";
        break;
        
         case "ACC201":
           $riskScore = FACC201($major); 
           break;
          
         case "AST222": 

          $riskScore = Fast222($satmath);
          break;
      
         case "BIO105":
         $riskScore = Fbio105($major);
          break;
          
         case "BIO215":
         $riskScore = Fbio215($Hsaverage,$satverb);
          break;
          
         case "BUS101":
         $riskScore = Fbus101($Hsaverage,$major);
          break;
          
         case "BUS105":
         $riskScore = Fbus105($Hsaverage, $major);
         break;
          
         case "CET102":
         $riskScore = Fcet102($Hsaverage, $satverb, $satmath);
          break;
          
         case "ECO110":
         $riskScore = Feco110($satmath,$major);
         break;
          
         case "ENG101":
         $riskScore = Feng101($Hsaverage,$major);
          break;
          
         case "ESC110":
         $riskScore = Fesc110($Hsaverage,$satmath);
          break;
          
         case "CET101":
         $riskScore = Fcet101($Hsaverage,$satverb,$satmath);
          break;
          
         case "CHE110":
         $riskScore = Fche110($Hsaverage);
          break;
          
         case "CHE130":
         $riskScore = Fche130($satverb,$satmath);
          break;
          
         case "COM112":
         $riskScore = Fcom112($Hsaverage,$satmath,$major);
          break;
          
         case "CS100":
         $riskScore = Fcs100($satmath);
          break;
          
         case "CS108":
         $riskScore = Fcs108($Hsaverage);
          break;
          
         case "CTC162":
         $riskScore = Fctc162($Hsaverage);
          break;
          
         case "HIS101":
         $riskScore = Fhis101($Hsaverage,$major);
          break;
          
         case "HIS102":
         $riskScore = Fhis102($Hsaverage);
          break;
          
         case "IDS102":
         $riskScore = Fids102($Hsaverage);
          break;
          
         case "IDS103":
         $riskScore = Fids103($Hsaverage);
          break;
          
         case "MAT110":
         $riskScore = Fmat110($Hsaverage,$major);
          break;
          
         case "MAT112":
         $riskScore = Fmat112($Hsaverage);
          break;
          
         case "MAT115":
         $riskScore = Fmat115($satmath,$Hsaverage);
          break;
          
         case "MAT120":
         $riskScore = Fmat120($Hsaverage,$major);
          break;
          
         case "MAT121":
         $riskScore = Fmat121($Hsaverage,$satmath);
          break;
          
          case "MAT122":
          $riskScore = Fmat122($Hsaverage,$satverb,$satmath);
          break;
          
          case "MAT151":
          $riskScore = Fmat151($satma,$Hsaverage);
          break;
          
          case "MAT152":
          $riskScore = Fmat152($Hsaverage);
          break;
          
          case "MAT230":
          $riskScore = Fmat230($Hsaverage,$satverb,$satmath,$major);
          break;
          
          case "MAT253":
          $riskScore = fmat253($Hsaverage,$satmath,$major);
          break;
          
          case "MTC101":
          $riskScore = Fmtc101($Hsaverage);
          break;
          
          case "NCS181":
          $riskScore = Fncs181($Hsaverage);
          break;
          
          case "PHY101":
          $riskScore = Fphy101($Hsaverage, $satverb,$satmath);
          break;
          
          case "PHY102":
          $riskScore = Fphy102($Hsaverage,$satverb,$satmath);
          break;
          
          case "PHY201":
          $riskScore = Fphy201($Hsaverage);
          break;
          
          case "PHY202":
          $riskScore = Fphy202($Hsaverage,$satmath);
          break;
          
          case "PSY100":
          $riskScore = Fpsy100($Hsaverage);
            break;
          
          case "SOC100":
          $riskScore = Fsoc100($Hsaverage);
          break;
          
        case "SPA101":
        $riskScore = Fspa101($Hsaverage,$major);
          break;
          
        case "STA101":
        $riskScore = Fsta101($Hsaverage);
          break;
          
	default:
	echo "Please select a class to assess";

            }//end of switch

	showrisk($riskScore,$classinput);
      }//end of else

     // execute function 
     // echo function results (risk score) color code$riskScore =d
    

    function showrisk ($riskScore,$class){

       $r = $riskScore;
       $c = $class;
       $level = "UNKNOWN";
          
       if ($r<10){$level = '<b style="color:green;">VERY LOW</b>';}
        elseif ($r<20){$level = '<b style="color:green;">LOW</b>';}
        elseif ($r<25){$level = '<b style="color:orange;">MODERATE</b>';}
	elseif ($r<30){$level = '<b style="color:orange;">HIGH AVERAGE</b>';}
	elseif ($r<40){$level = '<b style="color:red;">HIGH</b>';}
	else {$level ='<b style="color:red;">VERY HIGH</b>';}      

      echo "<br><p><b> Your risk score for ".$c." is: ".$r." </b><br> This is considered to be a ".$level." risk class for you.</p><br><br>"; 

	if ($r<10){echo "<p2>You should be able to take one or more classes of this risk level together without any difficulty.<br>Consider taking many low risk classes with one high risk class at a time to improve your chances of having a productive semester.</p2>";}
       
        elseif ($r<20){echo "<p>You should be able to take one or more classes of this risk level together without very much difficulty. Consider taking many low risk classes with one high risk class at a time to improve your chances of having a productive semester.</p>";}

	elseif ($r<25){echo "<p>You should be able to take one or two classes of this risk level together without too much difficulty, but consider spreading Moderte risk classses out over a few semesters to improve your chances of having a productive semester</p>";}
       
	elseif ($r<30){echo "<p>You should be able to take one or two classes of this risk level together without too much difficulty, but consider spreading High Average risk classses out over a few semiesters to improve your chances of having a productive semiester</p>";}
	
	elseif ($r<40){echo "<p>This class should be taken in a semiester with easier classes to improve your chances of passing this class and having a productive semester. This class will likely take some extra work on your part. If this class is not required for your major, you may want to consider avoiding it.</p>";}
	
	else {echo"<p>One or more factors put you at <i>High Risk</i> for failing this class. If this class is not required in your major, strongly consider avoiding it.<br> If this class is a requirement for your major, you shoudld not take this class with any high or moderate risk classes if possible, and take extra steps to prepare for the class material ahead of time. Fear not! No class is impossible to pass, this one is just going to take extra work</p>";} 

       
    }




    
    function Facc201 ($MAJOR = "UND"){
      
      $risk = 0;
      
      if( ($MAJOR == "ACC")or($MAJOR == "CIS")or($MAJOR == "CET")or($MAJOR =="CE")or($MAJOR =="CID")or($MAJOR =="PSY")or($MAJOR =="NCS"))
      {$risk=2;}
      elseif(($MAJOR=="BUS")or($MAJOR=="UND"))
      {$risk=18;}
      else if (($MAJOR=="CSCI")or($MAJOR=="HIM")or($MAJOR=="MET")or($MAJOR=="AM")or($MAJOR=="CSBM")or($MAJOR=="EET")or($MAJOR=="CIVET")or($MAJOR=="BIO"))
      {$risk=60;}
      else {$risk=1337;
      echo "somebody done goofed ";}
      
      return $risk;
      
    }
    
    function Fast222 ($MATH){
      $risk = 0;
      if ($MATH<=480)
      {$risk = 38;}
      else
      {$risk = 14;}
      
      return $risk;

    }
    
    function Fbio105($major){
      
      $risk=0;
      
      if (($major=="SOC")or($major=="INT")or($major=="PSY")or($major=="CSBM")or($major=="HIM")or($major=="UND")or
     ($major=="MET")or($major=="CIDBM"))
        {$risk=0;}
      elseif (($major=="CSCI")or($major=="CivET")or($major=="CE")or($major=="NUR")or($major=="BUS")or($major=="CID")or($major=="CIS")or($major=="ACC"))
          {$risk=26;}
      elseif(($major=="EET")||($major=="CET")||($major=="IMGD")or($major=="NCS")or($major=="CBH"))
           {$risk=100;}
      else
       $risk=1337;
 
 
 return $risk;
      
    }
    
    function Fbio215($hsavg, $verbal){
      
      $risk = 0;
      
      if ($hsavg<=86.2)
      {$risk=50;}
      else if ($verbal<=420)
      {$risk=50;}
      else
      {$risk=8;}
      
     return $risk;
      
      
    }
    
    
    
    function Fbus101 ($hsavg, $major){
      
      $risk = 0;
      
    if (($major == "CSCI")or($major == "CivET")or($major == "CE")or($major == "EET")) {
       {if ($hsavg <= 87.7)
           {$risk=82;}
     else
           {$risk=22;}
        }
    
   
     }
  else if (($major=="UND")||($major=="PSY")||($major=="BUS")||($major=="CID")||($major=="CIS")||($major=="SOC")||($major=="CSBM")||($major=="ACC")||($major=="CET")||($major=="CET")||($major=="ECE")||($major=="NCS")||($major=="ME")||($major=="CIDBM"))
     
     {if ($hsavg<=87.3)
            {$risk=24;}
      else
            {$risk=6;}
     }
  else{
    $risk=999;
  }
  
  return $risk;
      
    }
    
    
function Fbus105($hsavg, $major){

$risk = 0;

if ($hsavg <= 84.8) {
  $risk = 13;
}

elseif ($hsavg<=87.1) {
  if (($major == "ACC")or($major == "UND")or($major == "CET")or($major == "CSCI")) {
    $risk = 73;
}
elseif (($major == "PSY")or($major == "BUS")or($major == "NCS")) {
  $risk = 7;
}
else {$risk = 999;}
}
else {$risk = 3;}

return $risk;

}

function Fcet102($hsavg, $verbal, $math)
{

$risk = 0;

 if ($hsavg <= 84.6) {

  if ($math <= 560) 
  {$risk = 75;}
  elseif ($math <= 620) 
    {$risk = 0;}
  else {$risk = 91;}
  
   }

else if ($hsavg<=89.7){

  if ($verbal<=460)
     {$risk=49;}
   else if ($verbal<=550)
     {$risk=29;}
   else
     {$risk=71;}
  
  }
 else if ($verbal<=460){
  $risk=7;
}
 else{
  $risk=38;
}
 
 return $risk;
}


function Feco110 ($math,$major){


$risk = 0;

if (($major=="BUS")or($major=="CSCI")or($major=="CIS")or($major=="ACC")or($major=="UND")or($major=="CSBM")or($major=="MET")or($major=="ECE")or($major=="CID")) {
  
  if ($math<=605)
   {$risk = 18;}
 else 
  {$risk = 53;}

}
elseif (($major=="NCS")or($major=="CE")or($major=="EET")or($major=="CET")or($major=="BIO")or($major=="ME")) 
  {$risk = 68;}
else {$risk = 999;}


return $risk;

}





function Feng101($hsavg, $major)
{
 $risk = 0;

  if ($hsavg<=82.8) {
    $risk=38;
  }
  else if ($hsavg<=89.9)
    {if (($major=="BIO")or($major=="ECE")or($major=="MET")or($major=="CSBM")or($major=="CIS")or($major=="NCS")or($major=="CET")or($major=="ACC"))
     {$risk=21;}
     else if (($major=="CSCI")or($major=="ME")or($major=="PSY")or($major=="UND")or($major=="CivET")or($major=="CE")or($major=="HIM")or($major=="CIDBM")) 
     
      {$risk=7;}
     else if (($major=="AM")or($major=="EET")or($major=="CID"))
          {$risk=53;}
     else 
      {$risk=17;}
    }
  else 
    {$risk=6;}


return $risk;


}

function Fesc110($hsavg,$math)
{ 

  $risk=0;


 if ($math<=455)
   {$risk=29;}
 else if ($hsavg<=91.9)
   {$risk=7;}
 else 
  {$risk=0;}
 return $risk;
}



function Fcet101($math)
{

  $risk = 0;
 

 if ($math<=565){
    if ($math<=555)
       {$risk=28;}
   else{$risk=63;}
 }
 else
   {$risk=8;}
 

 return $risk;
}

function Fche110($hsavg)
{
  $risk=0;
 

 if ($hsavg<=82.0)
      {$risk=20;}
 else if ($hsavg<=84.6)
      {$risk=60;}
 else if ($hsavg<=86.1)
      {$risk=0;}
 else if ($hsavg<=89.2)
      {$risk=30;}
 else
      {$risk=8;}
 


return $risk;
}





function Fche130($verbal,$math)
{

$risk = 0;

if ($math <= 475) {
  $risk = 70;
}
elseif ($verbal <=475) {
  $risk = 33;
}
else
  {$risk = 7;}

return $risk;

}





function Fcom112($hsavg,$math,$major)
{$risk = 0;
  if (($major=="MET")or($major=="CID")or($major=="NCS")or($major=="CIDBM")or($major=="BUS")or($major=="CE")or($major=="PSY")or($major=="CIS")or($major=="CBH")or($major=="UND")or($major=="HIM")or($major=="SOC"))
         {$risk=13;}
  else if (($major=="CET")or($major=="ECE")or($major=="CSBM")or($major=="CSCI")or($major=="CivET")or($major=="ACC")or($major=="EET")or($major=="ME"))
      {if ($hsavg<=90.8)
            {$risk=44;}
       else
            {$risk=13;}
      }
  else if (($major=="BIO")or($major=="IMGD"))
     {if ($math<=500)
            {$risk=33;}
      else
            {$risk=100;}
     }
  else
     {$risk=999;}
  return $risk;
}



function Fcs100 ($math){

$risk = 0;

if ($math<=530) {
  $risk = 0;
}
elseif ($math<=550) {
  $risk = 33;
}
else{$risk =2;}

return $risk;
}



function Fcs108($hsavg){ 
  

  $risk = 0;
  

  if ($hsavg<=83.4) 
    {$risk=47;}
  else if ($hsavg<=91.2) 
    {$risk=26;}
  else 
    {$risk=11;}
  

  return $risk;
}





function Fctc162($hsavg)
{
 $risk = 0;


 if ($hsavg<=86.5)
    {$risk=19;}
 else
    {$risk=4;}


 return $risk;
}



function Fhis101 ($hsavg, $major)
{ $risk= 0;
 if ($hsavg<=84.0)
    {$risk=22;}
 else if (($major=="CET")||($major=="CSCI")||($major=="CSBM")||($major=="EET")||($major=="CE"))
    {$risk=12;}
 else if (($major=="MET")||($major=="UND")||($major=="CIS")||($major=="SOC")||($major=="ME")||($major=="ECE")||($major=="BIO")||($major=="BUS")||($major=="NCS")||($major=="CivET")||($major=="PSY"))
    {$risk=2;}
 else 
  {$risk=7;}
 return $risk;
}




function Fhis102 ($hsavg)
{ 

 $risk= 0;


  if ($hsavg<=83.7)
     {$risk=44;}
  else if ($hsavg<=88.8)
     {$risk=14;}
  else
     {$risk=1;}
  

  return $risk;
}





function Fids102($hsavg)
{
  $risk = 0;
 

 if ($hsavg<=82)
    {$risk=50;}
 else if ($hsavg<=86)
    $risk=19;
 else if ($hsavg<=87.5)
    {$risk=62;}
 else
    {$risk=11;}
 


 return $risk;
}




function Fids103($hsavg)
{

  $risk=0;
 

 if ($hsavg<=86.0)
      {$risk=51;}
 else
      {$risk=7;}
 

 return $risk;
}





function Fmat110 ($hsavg,$major)
{ 
  $risk = 0;
 
 if (($major=="CET")||($major=="NCS")||($major=="CSCI")||($major=="CIS")||($major=="PSY")||($major=="BIO"))
    {if ($hsavg<=87.5)
       {$risk=36;}
     else
       {$risk=5;}
    }
  else if (($major=="ACC")||($major=="BUS")||($major=="UND")||($major=="AM")||($major=="CivET")||($major=="MET")||($major=="CID")||($major=="CIDBM")||($major=="EET")||($major=="CSBM")||($major=="SOC")||($major=="ME"))
     {if (($major=="BUS")||($major=="EET"))
           {$risk=13;}
      else
           {$risk=0;}
     }
 else 
  {$risk=999;}
 

 return $risk;
}




function Fmat112($hsavg)
{

  $risk = 0;
 

 if ($hsavg<=85.9)
    {$risk=50;}
 else if ($hsavg<=88.9)
    {$risk=34;}
 else
    {$risk=18;}
 

 return $risk;
}


function Fmat115($math,$hsavg)
{
 
  $risk=0;
 

 if ($math<=525)
   {if ($hsavg<=83.5)
       {$risk=67;}
    else
       {$risk=28;}
   }
 else
   {$risk=12;}
 

 return $risk;
}



function Fmat120($hsavg,$major)
{ 
  $risk=0;
 

 if ($hsavg<=86.0)
   {if (($major=="MET")||($major=="EET")||($major=="UND")||
        ($major=="ME"))
    {$risk=82;}
    else if (($major=="CET")||($major=="CE")||($major=="ECE"))
       {$risk=50;}
    else
       {$risk=999;}
   }
 else
   {$risk=25;}


 return $risk;
}



function Fmat121 ($hsavg,$math)
{

  $risk=0;
  

  if ($hsavg<=85.7)
    {if ($math<=625)
       {$risk=50;}
     else
       {$risk=83;}
    }
  else if ($hsavg<=86.0)
     {$risk=100;}
  else if ($math<=525)
     {$risk=51;}
  else
     {$risk=24;}
  

  return $risk;
}


function Fmat122($hsavg,$verbal, $math)
{

 $risk = 0;
 

 if ($hsavg<=87.9)
   {if ($verbal<=505)
       {$risk=45;}
    else
       {$risk=77;}
   }
 else if ($math<=655)
     {$risk=38;}
 else
     {$risk=0;}


 return $risk;
}


function Fmat151 ($math) {

  $risk = 0;
 

 if ($math<=500) 
  {$risk=30;}
 else
   {$risk=13;}
 

 return $risk;
}


function Fmat152($hsavg)
{ 

  $risk=0;
  

  if ($hsavg<=94.5)
    {$risk=45;}
  else
    {$risk=0;}
  

  return $risk;
}






function Fmat230 ($hsavg,$verbal, $math, $major)
{
  $risk = 0;
 if ($hsavg<=86.3)
    {if (($major=="MET")||($major=="CivET")||($major=="EET")||($major=="CET"))
            {if($math<=525)
                {$risk=42;}
            else
                {$risk=87;}
            }
     else if (($major=="ECE") || ($major=="CSCI"))
             {$risk=25;}
     else 
      {$risk=999;}
    }
 else if ($hsavg<=92.6)
    {if ($verbal<=515)
           {$risk=25;}
     else
           {$risk=44;}
    }
 else
    {$risk=13;}
 

 return $risk;

}



function Fmat253($hsavg,$math,$major)
{

 $risk = 0;

 if (($major=="AM")||($major=="MET")||($major=="BIO")||($major=="CSCI"))
    {if ($math<=515)
             {$risk=71;}
     else if ($hsavg<=97) 
      {$risk=15;}
             else
               {$risk=47;}
    }
 else if (($major=="CSBM")||($major=="ME")||($major=="CET")||($major=="CE")||($major=="EET")||($major=="UND"))
    {if ($hsavg<=84)
          {$risk=11;}
     else
          {$risk=47;}
    }
 else
      {$risk=999;}


return $risk;
}


function Fmtc101($hsavg){ 

  $risk = 0;

  if ($hsavg<=81.2) {
    $risk = 71;
  }
  elseif ($hsavg<=83.2) {
    $risk = 28;
  }
  elseif ($hsavg<=88.5) {
    $risk = 6;
  }
  else{$risk = 0;}

  return $risk;

}

function Fncs181 ($hsavg)
{
  $risk=0;
 
 if ($hsavg<=83.1)
    {$risk=75;}
 else
    {$risk=18;}
 
 return $risk;
}




function Fphy101($hsavg, $verbal, $math)
{
 $risk=0;

  if ($hsavg<=83.0) 
    {$risk=90;}
  else if ($hsavg<=88.1)
   {if ($math<=460) 
    {$risk=80;}
    else if ($math<=520) 
      {$risk=22;}
    else if ($math<=530) 
      {$risk=75;}
    else 
      {$risk=17;}
   }
  else if (verbal<=430) 
    {$risk=25;}
  else if (verbal<=500) 
    {$risk=44;}
  else 
    {$risk=6;}
  

  return $risk;

}

function Fphy102 ($hsavg,$verbal,$math)
{

 $risk=0;

 if ($hsavg<=84.2)
  {if ($math<=540)
      {$risk=78;}
   else
      {$risk=0;}
  }
 else if ($hsavg<=86.6)
    {$risk=30;}
 else if ($hsavg<=91.1)
   {if ($verbal<=440)
      {$risk=33;}
    else if ($verbal<=500)
      {$risk=0;}
    else
      {$risk=21;}
   }
 else if ($hsavg<=92)
      {$risk=0;}
 else
      {$risk=14;}
 
 return $risk;
}


function Fphy201($hsavg) // 333333333333333333333333333333333333333333333333333333333333333333
{

  $risk=0;
 
 if ($hsavg<=90.6)
    {$risk=68;}
 else if ($hsavg<=93.8)
    {$risk=46;}
 else
    {$risk=18;}
 
 return $risk;
}



function Fphy202($hsavg,$math)
{ 
  $risk=0;
  
  if ($hsavg<=88.9)
    {if ($math<=560)
        {$risk=35;}
     else
        {$risk=87;}
    }
  else
    {$risk=36;}
  
  return $risk;
}




function Fpsy100($hsavg)
{
  $risk=0;
 
 if ($hsavg<=88.0)
    {$risk=14;}
 else
    {$risk=1;}
 
 return $risk;
}





function Fsoc100($hsavg)
{
  $risk=0;
 
 if ($hsavg<=84.2) 
  {$risk=38;}
 else if ($hsavg<=92.0)
  {$risk=9;}
 else 
  {$risk=0;}


 return $risk;
}



function Fspa101($hsavg,$major)
{
  $risk=0;
 
 if (($major=="MET")||($major=="UND")||($major=="PSY")||($major=="NCS")||($major=="BUS")||($major=="ECE")||($major=="CivET")||($major=="CIS")||($major=="CID")||($major=="CET")||($major=="CBH")||($major=="EET")||($major=="CSBM")||($major=="SOC")||($major=="IMGD"))
       {$risk=5;}
 else if (($major=="ACC")||($major=="CSCI")||($major=="ME")||($major=="CE")||($major=="AM")||($major=="BIO")||($major=="CIDBM"))
            {if ($hsavg<=87.1)
                 {$risk=17;}
             else
                 {$risk=39;}
            }
 else
   {$risk=999;}
 
 return $risk;
}

function Fsta101($hsavg)
{
  $risk=0;

 if ($hsavg<=83.5)
    {$risk=56;}
 else if ($hsavg<=89.1)
    {$risk=34;}
 else
    {$risk=20;}
 
 return $risk;
}

  ?>
    </body>
</html>














